DROP table APP.CUSTOMER_COUPON;
DROP table APP.COMPANY_COUPON;
DROP table APP.Company;
DROP table APP.Customer;
DROP table APP.Coupon;

CREATE TABLE APP.Company
(
	ID BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	COMP_NAME VARCHAR(20) NOT NULL UNIQUE,
	PASSWORD VARCHAR(20) NOT NULL,
	EMAIL VARCHAR(40)
);

CREATE TABLE APP.Customer
(
	ID BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	CUST_NAME VARCHAR(20) NOT NULL UNIQUE,
	PASSWORD VARCHAR(20) NOT NULL
);

CREATE TABLE APP.Coupon
(
	ID BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) ,
	TITLE VARCHAR(70) NOT NULL UNIQUE,
	START_DATE DATE not null,
	END_DATE DATE not null,
	AMOUNT INTEGER not null,
	COUPON_TYPE VARCHAR(12) not null,
	MESSAGE VARCHAR(500),
	PRICE DOUBLE not null,
	IMAGE VARCHAR(50)
);

CREATE TABLE APP.CUSTOMER_COUPON
(
	CUST_ID BIGINT REFERENCES APP.CUSTOMER (ID),
	COUPON_ID BIGINT REFERENCES APP.COUPON (ID),
	PRIMARY KEY (CUST_ID, COUPON_ID)
);

CREATE TABLE APP.COMPANY_COUPON
(
	COMP_ID BIGINT  REFERENCES APP.COMPANY (ID),
	COUPON_ID BIGINT REFERENCES APP.COUPON (ID),
	PRIMARY KEY (COMP_ID, COUPON_ID)
);